meta_product_name: ""
meta_title: "Axel Ridray | Développeur Web Full Stack Junior"
meta_description: "Portfolio réaliser avec Ruby rails, HTML/CSS/SCSS et Javascript "
meta_image: "cover.jpg" # should exist in `app/assets/images/`
